#!/bin/bash

# Convenience script for running specs within the latest official container

docker run \
    --rm \
    --volume `pwd`:/data \
    --workdir /data \
    crystallang/crystal \
    crystal spec --progress $*
